// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa2Zhbh1XvXMMWhkGkPivrO5x500j6jIo',
    appId: '1:819375579182:web:0410ab57b093273399bfbf',
    messagingSenderId: '819375579182',
    projectId: 'touristapp-b02be',
    authDomain: 'touristapp-b02be.firebaseapp.com',
    storageBucket: 'touristapp-b02be.appspot.com',
    measurementId: 'G-C6J9S572F4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCGfZGQOoLPwWuCG1a_GQT-XkgSqRX5Yc',
    appId: '1:819375579182:android:769173a0137e268999bfbf',
    messagingSenderId: '819375579182',
    projectId: 'touristapp-b02be',
    storageBucket: 'touristapp-b02be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfIesk6L7zn7SKyxSEtAj-jwXAZmPWjXE',
    appId: '1:819375579182:ios:f23a6b5acaea9f0199bfbf',
    messagingSenderId: '819375579182',
    projectId: 'touristapp-b02be',
    storageBucket: 'touristapp-b02be.appspot.com',
    iosClientId: '819375579182-kcu6ntv5571h03dsdeldp00o8oifv9sl.apps.googleusercontent.com',
    iosBundleId: 'com.example.touristApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfIesk6L7zn7SKyxSEtAj-jwXAZmPWjXE',
    appId: '1:819375579182:ios:f23a6b5acaea9f0199bfbf',
    messagingSenderId: '819375579182',
    projectId: 'touristapp-b02be',
    storageBucket: 'touristapp-b02be.appspot.com',
    iosClientId: '819375579182-kcu6ntv5571h03dsdeldp00o8oifv9sl.apps.googleusercontent.com',
    iosBundleId: 'com.example.touristApp',
  );
}
